name: aes_latency_test
description: A command-line application to test AES encryption latency.
version: 1.0.0
environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  encrypt: ^5.0.3
  intl: ^0.18.0 # For timestamp formatting
  path: ^1.8.3
